### ISSUE TITLE
Runway删库跑路了 

### ISSUE THREAD

**Issue by wbuqamdi** [Jeff-LiangF/streamv2v#10]
大佬们  Runway删库跑路了  Stable Diffusion v1.5都删没了  现在新部署项目没法用了   
<img width="966" alt="1726233185132" src="https://github.com/user-attachments/assets/ede90214-7fdb-4808-a63e-bff0b4b30e11">

**Comment by Jeff-LiangF** [comment]
Hello @wbuqamdi ,

谢谢你的关注，我们已经将 "runwayml/stable-diffusion-v1-5" 替换为一个镜像 “Jiali/stable-diffusion-1.5”. 更多信息请查看这个[链接](https://huggingface.co/posts/dn6/357701279407928).

Thanks for your interest. We have replaced the default "runwayml/stable-diffusion-v1-5" with another mirror “Jiali/stable-diffusion-1.5”. More information please check this [link](https://huggingface.co/posts/dn6/357701279407928).

**Comment by wbuqamdi** [comment]
Thanks very much @Jeff-LiangF
