### ISSUE TITLE
Regarding the new components EA, FF, and DyMe

### ISSUE THREAD

**Issue by zjysteven** [Jeff-LiangF/streamv2v#3]
Hi,

Thank you for the great work and open-sourcing the code. I was wondering if you could kindly point us to where the new components (EA, FF, DyMe) are implemented. I'm asking this because in the StreamV2V pipeline class https://github.com/Jeff-LiangF/streamv2v/blob/main/src/streamv2v/pipeline.py I fail to identify where and how the 3 new components take effect (in other words I fail to see the difference between StreamV2V pipeline and StreamDiffusion pipeline).

Thanks

**Comment by Jeff-LiangF** [comment]
Hi @zjysteven,

Thanks for your interest in our work. The flow is: (1). we [swap](https://github.com/Jeff-LiangF/streamv2v/blob/main/utils/wrapper.py#L516) the attn_processors with our own [cached_attn_processors](https://github.com/Jeff-LiangF/streamv2v/blob/main/src/streamv2v/models/attention_processor.py#L173) if we want to use new components (EA, FF, DyMe) (2). use [EA](https://github.com/Jeff-LiangF/streamv2v/blob/main/src/streamv2v/models/attention_processor.py#L291C1-L297C76) to add keys and values in the cached feature bank. (3). use [FF](https://github.com/Jeff-LiangF/streamv2v/blob/main/src/streamv2v/models/attention_processor.py#L334C1-L339C111) to fuse the output. (4). use [DyMe](https://github.com/Jeff-LiangF/streamv2v/blob/main/src/streamv2v/models/attention_processor.py#L341-L348) if you want to use token merging.

The advantage of this implementation is that we do minimal modification and can seamlessly coordinate with StreamDiffusion if we have new features.

I closed this issue. Feel free to reopen it if you have further questions. Thanks!

**Comment by zjysteven** [comment]
Thanks! These are helpful.
