### ISSUE TITLE
What kind of crappy project is this?

### ISSUE THREAD

**Issue by haisheng666** [Jeff-LiangF/streamv2v#5]
What kind of crappy project is this? How do I use it? The wrapper.py file in utils obviously lacks the sys and os modules, don't you know?

**Comment by Jeff-LiangF** [comment]
Please follow the [installation guide ](https://github.com/Jeff-LiangF/streamv2v/blob/main/INSTALL.md). You won't have any issues if you do it right.

Also, please specify your problems so that the community can help you.
